apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transitops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.transitops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transitops-api
                port:
                  number: 80
    - host: web.transitops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transitops-web
                port:
                  number: 80